spring.application.name=interview-system

# ── Local MySQL (for development) ──────────────────────────
# spring.datasource.url=jdbc:mysql://localhost:3306/interview_system
# spring.datasource.username=root
# spring.datasource.password=root

# ── PostgreSQL (Render) ─────────────────────────────────────
spring.datasource.url=jdbc:postgresql://dpg-d73rp2dm5p6s73et7kig-a:5432/interview_system_db
spring.datasource.username=interview_system_db_user
spring.datasource.password=IP8sfKTKnLbakS4QdZCImdxgMwmddjXj
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Fix: serialize LocalDateTime as ISO strings, not arrays
spring.jackson.serialization.write-dates-as-timestamps=false

server.port=${PORT:8080}

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000